name: Quality checks

on:
  push:
    paths-ignore:
      - '**.yml'
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3.5.0
        with:
          node-version: "14.x"
      - name: Install dependencies
        run: npm ci
      - name: Prettier
        run: npm run format
      - name: Ensure consistency
        run: npm run lint
